# Generated by Django 4.2 on 2023-06-02 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_contact_addr', models.CharField(max_length=40)),
                ('number_of_reports', models.IntegerField(default=0)),
                ('midReport', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_state', models.CharField(choices=[('OPEN', 'Open'), ('AWCT', 'Awaiting Category'), ('DONE', 'Done')], default='OPEN', max_length=4)),
                ('categoria', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('authorId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wppbot.chatbotuser')),
            ],
        ),
    ]
