# Generated by Django 4.2 on 2023-06-04 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wppbot', '0002_rename_authorid_report_author_report_datecreated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_state',
            field=models.CharField(choices=[('AWCT', 'Awaiting Category'), ('AWDC', 'Awaiting Description'), ('CFDC', 'Awaiting Description'), ('AWLC', 'Awaiting Localization'), ('DONE', 'Done')], default='AWCT', max_length=4),
        ),
    ]
